### ISSUE TITLE
Query re landcover dataset, watched Cloud Next'19 video and tried to find out more

### ISSUE THREAD

**Issue by kitmacleod** [GoogleCloudPlatform/earth-ml#2]
Hi, I am a huge fan of GEE (great platform and learning resources esp. linking with TF etc). I just caught up on Nick, Chris and David's talk re 2013-18 global landcover map "What Is on Earth: A Big Data Problem (Cloud Next '19)". What are your plans for making the outputs available? I have searched and all I found was this Github repo (great sharing). Thanks for any info. Sorry, this is not an 'issue' but could find no other way to contact Nick, Chris or David-feel free to close.

**Comment by davidcavazos** [comment]
You can see the results in the ImageCollection [`projects/project-earth/landcover`](https://code.earthengine.google.com/?asset=projects/project-earth/landcover). We don't have results for the entire world, only for certain areas we analyzed. You can visualize them in the code editor with this [script](https://code.earthengine.google.com/55eeefb8448ebe418e531fabbfd9ddc7).
